# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/066efb49-3aa4-41e1-85ae-eff9be2bdba5";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress-force=zstd:1"
      "noatime"
      "space_cache=v2"
      "discard=async"
      "ssd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/066efb49-3aa4-41e1-85ae-eff9be2bdba5";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress-force=zstd:1"
      "noatime"
      "space_cache=v2"
      "discard=async"
      "ssd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/066efb49-3aa4-41e1-85ae-eff9be2bdba5";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress-force=zstd:1"
      "noatime"
      "space_cache=v2"
      "discard=async"
      "ssd"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/066efb49-3aa4-41e1-85ae-eff9be2bdba5";
    fsType = "btrfs";
    options = [
      "subvol=@var"
      "compress-force=zstd:1"
      "noatime"
      "space_cache=v2"
      "discard=async"
      "ssd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0CA2-4CE2";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
